// Keep client acceptance and the incremental SQL migration in sync.
export const TERMS_VERSION = '2.0';
export const LEGAL_DATE = '10 de outubro de 2026';
export const PRIVACY_EMAIL = 'aquecimentoapp@gmail.com';
export const CONTROLLER_NAME = 'João António Pires Martins dos Santos Rodrigues';

export const termsSections = [
  { title: '1. Responsável e independência', text: `O Aquecimento é um projeto independente gerido por ${CONTROLLER_NAME}. Contacto: ${PRIVACY_EMAIL}. Não representa a Universidade de Coimbra nem tem afiliação, aprovação, endosso ou suporte oficial da universidade. O domínio do email serve apenas como critério de acesso.` },
  { title: '2. Quem pode utilizar', text: 'O acesso é reservado a pessoas com 18 ou mais anos e endereço @student.uc.pt. Ao aceitar estes termos, declaras que tens pelo menos 18 anos. A verificação do email confirma o controlo desse endereço, não a idade. Não podes ceder a conta ou fazer-te passar por outra pessoa.' },
  { title: '3. Serviço e disponibilidade', text: 'O serviço permite conversas temporárias entre participantes emparelhados. Os horários, limites e opções disponíveis são apresentados na aplicação e verificados pelo servidor. Podem ocorrer interrupções, falhas de entrega ou perda de histórico. O serviço não é um canal de emergência nem garante resposta imediata a denúncias.' },
  { title: '4. Conduta', text: 'Não são permitidos ameaças, assédio, discriminação, exploração sexual, conteúdos ilegais, divulgação não autorizada de dados de terceiros, spam ou tentativas de contornar os controlos de acesso. Não partilhes credenciais, documentos de identificação, dados íntimos ou outros dados sensíveis. Respeita a vontade do outro participante de terminar a conversa.' },
  { title: '5. Conversas e denúncias', text: 'O buffer temporário expira 5 minutos após a última mensagem nova. Mensagens já recebidas podem continuar no separador durante a sessão. O histórico pode estar incompleto. Uma denúncia termina a sala e guarda o conteúdo disponível no servidor, que pode ser parcial ou vazio. Retries não recuperam mensagens expiradas. O prazo de denúncia é de 5 minutos após o fim efetivo da sala. Não existe garantia de confidencialidade absoluta: o destinatário pode copiar o que recebe.' },
  { title: '6. Moderação e contacto', text: `As denúncias podem ser analisadas pelo responsável para avaliar incumprimentos e decidir restrições de acesso, incluindo suspensão. Podes contestar uma decisão ou comunicar conteúdo ilegal através de ${PRIVACY_EMAIL}, indicando os factos necessários, sem enviar dados excessivos. Não há encaminhamento automático de todas as conversas ou denúncias para autoridades; qualquer comunicação exige fundamento jurídico aplicável.` },
  { title: '7. Dados pessoais e eliminação', text: 'A Política de Privacidade explica os dados tratados, finalidades, conservação e direitos. Aceitar estes termos não é um consentimento genérico para qualquer tratamento de dados. Podes eliminar a conta nas Definições; isso não elimina imediatamente todos os dados de denúncias, buffers, registos técnicos ou cópias de segurança. Podes também exercer direitos pelo contacto de privacidade.' },
  { title: '8. Alterações e responsabilidade', text: 'Alterações materiais dos termos exigem nova aceitação antes de continuar a conversar. Não é garantida ausência de falhas, mas estes termos não excluem responsabilidades nem direitos que a lei torne obrigatórios. Aplica-se a lei portuguesa, sem afastar normas imperativas ou os meios legais de reclamação e recurso disponíveis ao utilizador.' },
];

export const privacySections = [
  { title: '1. Quem trata os dados', text: `O responsável pelo tratamento é ${CONTROLLER_NAME}, pessoa singular que gere o projeto independente Aquecimento. Para questões de privacidade e exercício de direitos: ${PRIVACY_EMAIL}. A Universidade de Coimbra não gere este projeto. O endereço institucional não estabelece uma ligação oficial; o prestador da tua caixa de email processa as mensagens de autenticação que te são enviadas.` },
  { title: '2. Dados e finalidades', text: 'Tratamos o email, identificador de conta, nome indicado, data de nascimento declarada, opção de género (incluindo «prefiro não divulgar»), datas de criação e aceitação dos termos, versão aceite e declaração de maioridade. O nome identifica o perfil privado e pode ser um nome de uso; a data permite validar a idade declarada no registo. O género é uma indicação facultativa do perfil, não é utilizado para emparelhar participantes. O Supabase Auth trata a password para autenticação; a aplicação não a guarda no perfil, em logs ou no armazenamento próprio do browser. Tratamos ainda identificadores de fila e sala, participantes, horários e estado de sessão; conteúdo e metadados das mensagens; sugestões de quebra-gelo; e denúncias, respetivo conteúdo disponível e estado. Os serviços de alojamento e autenticação também podem tratar IP, pedidos e registos técnicos para operação e segurança.' },
  { title: '3. Fundamentos do tratamento', text: 'A autenticação, o emparelhamento e a entrega de mensagens necessários à prestação do serviço baseiam-se na execução do contrato ou nas diligências pedidas pelo utilizador (artigo 6.º, n.º 1, alínea b), do RGPD). A prevenção de abuso, segurança, avaliação de denúncias e defesa de direitos são avaliadas com base em interesses legítimos, sujeitos à necessidade e ponderação dos direitos dos titulares (alínea f)). Obrigações legais concretamente aplicáveis podem exigir tratamentos adicionais (alínea c)). Não utilizamos a aceitação dos termos como autorização ilimitada. Não solicitamos dados de saúde, vida sexual ou outras categorias especiais; não os partilhes nas mensagens. O seu eventual tratamento exige avaliação e fundamento específico, não bastando o interesse legítimo.' },
  { title: '4. Mensagens e retenção', text: 'As mensagens comuns não são arquivadas como histórico permanente no PostgreSQL. O buffer Redis expira 5 minutos depois da última mensagem nova; cada mensagem nova renova o prazo do buffer inteiro. Metadados de deduplicação, incluindo identificadores e resumo criptográfico do texto, expiram 10 minutos depois da última mensagem nova. O separador conserva mensagens recebidas em sessionStorage durante a sessão, podendo haver recuperação pelo próprio browser. Fechar ou limpar a sessão não apaga cópias feitas pelo destinatário.' },
  { title: '5. Denúncias e restantes dados', text: 'Uma denúncia guarda no Supabase o conteúdo ainda disponível, com identificadores, data e estado. A limpeza periódica remove denúncias com mais de 30 dias; falhas ou atrasos podem prolongar a conservação até à limpeza efetiva. A conta e perfil mantêm-se enquanto a conta existir; podes eliminá-los nas Definições. As referências ao perfil nas denúncias são removidas nessa eliminação, mas o texto pode continuar a identificar pessoas. A limpeza remove salas após o limite absoluto de fecho mais um dia. Sugestões podem permanecer sem a referência à conta após a eliminação; evita dados pessoais nesses textos. Registos técnicos e backups dos fornecedores têm ciclos próprios e não são apagados instantaneamente com a conta.' },
  { title: '6. Quem pode receber dados', text: 'O outro participante recebe as mensagens que envias e identificadores técnicos necessários à conversa, não o teu email, nome, data de nascimento ou género através do fluxo de chat. Os dados de registo são guardados no perfil privado e nos metadados de autenticação do Supabase; apenas o próprio utilizador e os serviços/responsável com acesso administrativo os podem consultar. Sugestões aprovadas podem aparecer aos participantes. O responsável pode aceder às denúncias para as avaliar. Supabase fornece autenticação, base de dados, Functions e Realtime; Upstash fornece o buffer Redis; Cloudflare aloja a aplicação. O fornecedor de email configurado para autenticação e o prestador da tua caixa de email tratam os dados necessários à entrega. Se contactares aquecimentoapp@gmail.com, a Google, prestadora dessa caixa, processa o conteúdo do teu pedido. Autoridades ou outros destinatários só recebem dados quando exista fundamento jurídico aplicável. Não vendemos dados pessoais nem usamos o conteúdo das mensagens para publicidade.' },
  { title: '7. Localização, segurança e limites', text: 'Os serviços externos podem envolver tratamento fora do Espaço Económico Europeu. As transferências que o exijam devem apoiar-se numa decisão de adequação ou noutras garantias previstas no RGPD; podes pedir informação sobre as garantias e obter cópia pelo contacto de privacidade. Os canais de sala são privados e o acesso é controlado pelo servidor. Isto não é encriptação ponta a ponta: os serviços que processam mensagens e denúncias podem aceder ao conteúdo no âmbito das suas funções. Nenhum serviço garante risco zero.' },
  { title: '8. Armazenamento no dispositivo', text: 'A aplicação utiliza armazenamento do browser para manter a sessão de autenticação e o contexto temporário do chat. Estes mecanismos servem a autenticação, continuidade e segurança do serviço; não constituem autorização para instalar rastreadores de publicidade. Podes limpar os dados do site no browser, o que pode terminar a sessão e remover o histórico local. Esta limpeza não elimina a conta no servidor.' },
  { title: '9. Os teus direitos', text: `Podes pedir acesso, retificação, apagamento, limitação e, quando aplicável, portabilidade dos dados, bem como opor-te ao tratamento baseado em interesses legítimos, através de ${PRIVACY_EMAIL}. Podemos pedir apenas a informação necessária para confirmar a identidade. Respondemos nos prazos legais, em regra um mês, comunicando qualquer extensão legalmente permitida. Os direitos têm condições e exceções previstas na lei. Podes apresentar reclamação à CNPD em www.cnpd.pt e recorrer aos meios judiciais aplicáveis.` },
  { title: '10. Idade e alterações', text: 'O serviço destina-se apenas a maiores de 18 anos. A data de nascimento é declarada no novo registo e validada no servidor; não recolhemos um documento nem comprovamos a idade real. As contas antigas mantêm a declaração de maioridade, sem data de nascimento inventada. Se souberes que um menor utiliza o serviço, contacta-nos para avaliação e restrição de acesso. Mudanças desta política serão identificadas por data. Se uma nova finalidade exigir consentimento específico, este será pedido separadamente e poderá ser retirado, sem afetar a licitude do tratamento anterior.' },
];
